import { defineStore } from "pinia";

//菜单列表
export const menuStore = defineStore('menu',{
    state(){
        return {
            menuList:[
                {
                    name:"首页",
                    value:"index",
                    path:"/index/myindex"
                },
                {
                    name:"我的店铺",
                    value:"myshop",
                    path:"/index/myshop",
                    children:[
                        {
                            value:"shopseting",
                            name:"店铺管理",
                            path:"/index/shopseting",
                        },
                        {
                            name:"订单管理",
                            value:"order",
                            path:"/index/order",
                        },
                        {
                            name:"客户管理",
                            value:"customer",
                            path:"/index/customer",
                        },
                        {
                            name:"员工管理",
                            value:"mystaff",
                            path:"/index/mystaff",
                        },
                        {
                            name:"商品管理",
                            value:"goods",
                            path:"/index/goods",
                        },
                    ]
                },
                {
                    value:"shopmanage",
                    name:"店铺管理",
                    path:"/index/shopmanage"
                },
                {
                    value:"goodsHouse",
                    name:"商品库",
                    path:"/index/goodsHouse"
                },
                {   
                    value:"system",
                    name:"系统设置",
                    path:"/index/system"
                },
            ],
            selectedMenu:[
                {
                    name:'首页',
                    path:"/index/myindex"
                }
            ]
        }
    },
})