

const api = {
    getShop:"getShop",
    addShop:"addShop",
    addDesposit:"addDesposit",
    getDesposit:"getDesposit",
    updateDesposit:"updateDesposit",
    getDesposits:"getDesposits",
    deleteDesposit:"deleteDesposit",
    addStaff:"addStaff",
    getStaff:"getStaff",
    updateStaff:"updateStaff",
    getStaffs:"getStaffs",
    deleteStaff:"deleteStaff",
    addCustomer:"addCustomer",
    getCustomer:"getCustomer",
    updateCustomer:"updateCustomer",
    getCustomers:"getCustomers",
    deleteCustomer:"deleteCustomer",
    logout:"/logout",
    deleteFile:"/deleteFile",
    sysAddBrand:"/sys/addBrand",
    sysGetBrandList:"/sys/getBrandList",
    sysUpdateBrand:"/sys/updateBrand",
    sysDeleteBrand:"/sys/deleteBrand",
    sysAddGoods:"/sys/addGoods",
    sysGetGoodsList:"/sys/getGoodsList",
    sysGetGoods:"/sys/getGoods",
    sysUpdateGoods:"/sys/updateGoods",
    sysDeleteGoods:"/sys/deleteGoods",
    sysGetCategorys:"/sys/getCategorys",
    sysAddCategory:"/sys/addCategory",
    sysGetCategory:"/sys/getCategory",
    sysUpdateCategory:"/sys/updateCategory",
    sysDeleteCategory:"/sys/deleteCategory",
    sysGetExpenseCategorys:"/sys/getExpenseCategorys",
    sysAddExpenseCategory:"/sys/addExpenseCategory",
    sysGetExpenseCategory:"/sys/getExpenseCategory",
    sysUpdateExpenseCategory:"/sys/updateExpenseCategory",
    sysDeleteExpenseCategory:"/sys/deleteExpenseCategory",
}

export default api;